# Generated by Django 6.0.6 on 2026-06-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'continent',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='worldcup.continent')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='worldcup.country')),
            ],
            options={
                'db_table': 'city',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='WorldCup',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('home_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='world_cups_home_1', to='worldcup.country')),
                ('home_country_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='world_cups_home_2', to='worldcup.country')),
                ('home_country_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='world_cups_home_3', to='worldcup.country')),
            ],
            options={
                'db_table': 'world_cup',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goals_country_1', models.CharField(max_length=20)),
                ('goals_country_2', models.CharField(max_length=20)),
                ('phase', models.CharField(max_length=100)),
                ('phase_rank', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('wikipedia', models.URLField(blank=True)),
                ('country_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_country_1', to='worldcup.country')),
                ('country_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_country_2', to='worldcup.country')),
                ('home_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='worldcup.city')),
                ('home_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_games', to='worldcup.country')),
                ('world_cup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='worldcup.worldcup')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
