# Generated by Django 6.0.6 on 2026-06-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcup',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_worldcups', to='worldcup.country'),
        ),
    ]
